"""
gen_fixtures.py — Generate onchain/test/fixtures.json from utils/merkle.py.

Run from repo root:
    python onchain/gen_fixtures.py

The output fixtures.json is consumed by:
  - HAICAnchor.t.sol (cross-language consistency test via vm.readFile)
  - Python test_anchor_client.py (TestCrossLanguageConsistency)

Regenerate whenever utils/merkle.py logic changes.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

# Allow running from repo root or from onchain/
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from utils.merkle import sha3_256_hex, merkle_root, hash_items_to_leaves

MESSAGES_3 = [
    {"role": "user",      "content": "Tell me about your AI use."},
    {"role": "assistant", "content": "[PIVOT: SHADOW] When did that start?"},
    {"role": "user",      "content": "Last month when my boss installed it."},
]

MESSAGES_1 = [
    {"role": "user", "content": "payload_single"},
]

leaves_3 = hash_items_to_leaves(MESSAGES_3)
leaves_1 = hash_items_to_leaves(MESSAGES_1)

fixtures = {
    "description": (
        "SHA3-256 digests produced by utils/merkle.py — cross-language verification. "
        "Regenerated by onchain/gen_fixtures.py. Do not edit by hand."
    ),
    "sessions": {
        "sess_42":          "0x" + sha3_256_hex("sess_42"),
        "sess_abc":         "0x" + sha3_256_hex("sess_abc"),
        "training_run_001": "0x" + sha3_256_hex("training_run_001"),
    },
    "roots": {
        "payload_single":     "0x" + sha3_256_hex("payload_single"),
        "three_message_tree": "0x" + merkle_root(leaves_3),
        "empty_tree":         "0x" + merkle_root([]),
        "one_message_tree":   "0x" + merkle_root(leaves_1),
    },
    "leaves": {
        "three_message": leaves_3,
        "one_message":   leaves_1,
    },
}

out = Path(__file__).resolve().parent / "test" / "fixtures.json"
out.write_text(json.dumps(fixtures, indent=2))
print(f"Written: {out}")
for k, v in fixtures["sessions"].items():
    print(f"  sessions.{k}: {v}")
for k, v in fixtures["roots"].items():
    print(f"  roots.{k}: {v}")
