"""
nla.py — Natural Language Autoencoder (NLA) inference interface.

This is the CONSUMER-side stub for the NLA capability being added to PRISM in
a parallel session (see docs/nla_integration_plan_2026-05-11.md). The full
implementation will live in `prism.nla` (D:/prism repo); this module is a
gemma4good-local interface that:

  - Defines the contract canonical_eval and the 5th governance tool consume.
  - Provides a working MockNLA for tests and CI (zero-GPU, deterministic).
  - Auto-detects whether the PRISM-side `prism.nla` is installed and adapts.

The contract follows Anthropic's NLA technique (Lee et al., 2026, available
at transformer-circuits.pub/2026/nla and github.com/kitft/natural_language_
autoencoders): an "Activation Verbalizer" (AV) maps a layer-l residual-stream
activation to a natural-language explanation, and an "Activation Reconstructor"
(AR) maps that explanation back to activation space. The forward-pass output
of NLA is the AV's text. The reconstruction FVE is a confidence signal
(higher = the AV's text captures more of the activation's content).

## Honest scope limits

  - No NLA is pre-trained for Gemma-4-E2B-it (our production family). The
    closest released checkpoint is `kitft/nla-gemma-3-12b-it-layer32`.
  - Training a new Gemma-4 NLA requires 16 H100s for the RL stage per
    Anthropic's recipe — well beyond Kaggle T4.
  - This module DOES NOT make claims about Gemma-4 internals using a
    Gemma-3 NLA. That would be methodologically broken. The 5th governance
    tool uses MockNLA on Gemma-4 today and waits for a Gemma-4 NLA to
    exist.

## Usage

```python
from prism_integration.nla import get_explainer, NLAExplanation

# Mock (always works, deterministic):
explainer = get_explainer("mock", d_model=1536, layer_idx=20)
result: NLAExplanation = explainer.explain(activation_vec)   # 1-D numpy array

# Real (when PRISM-side `prism.nla` is installed and an NLA is reachable):
explainer = get_explainer("kitft/nla-gemma-3-12b-it-layer32",
                          sglang_url="http://localhost:30000")
result = explainer.explain(activation_vec)
print(result.text)            # "The model is reasoning about geographic..."
print(result.reconstruction_fve)
```
"""

from __future__ import annotations

import hashlib
import logging
from dataclasses import asdict, dataclass, field
from typing import Optional, Protocol, runtime_checkable

logger = logging.getLogger(__name__)


@dataclass
class NLAExplanation:
    """Result of explaining a single activation vector.

    Schema is stable across MockNLA and PRISM's `prism.nla.NLAExplanation`.
    Both implementations produce this exact shape.

    Attributes
    ----------
    text : str
        The natural-language explanation generated by the AV.
    reconstruction_fve : float
        Fraction of Variance Explained for this single sample (in [0, 1]).
        Higher = the AV's text captures more of the activation's content.
        For MockNLA this is a deterministic function of the input hash;
        for real NLA it comes from the AR's reconstruction loss.
    model_id : str
        Identifier of the NLA used (e.g. "kitft/nla-gemma-3-12b-it-layer32"
        or "mock").
    layer_idx : int
        Index of the layer the activation was drawn from in the target model.
    activation_norm : float
        L2 norm of the input activation. For diagnosis only — high norms
        often coincide with low FVE.
    extra : dict
        Implementation-specific metadata (warnings, AR confidence, etc.).
    """

    text: str
    reconstruction_fve: float
    model_id: str
    layer_idx: int
    activation_norm: float
    extra: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)


@runtime_checkable
class NLAExplainerProtocol(Protocol):
    """Duck-typed contract for any NLA explainer (mock or real).

    Any object that implements `explain(activation_vector)` returning an
    NLAExplanation satisfies this protocol.
    """

    model_id: str
    layer_idx: int

    def explain(self, activation_vector) -> NLAExplanation: ...
    def explain_batch(self, activation_vectors) -> list[NLAExplanation]: ...


# ── MockNLA — deterministic, zero-dep ──────────────────────────────────────


@dataclass
class MockNLA:
    """Deterministic mock explainer for testing and CI.

    Properties:
      - No torch, no GPU, no network. Pure Python + numpy (numpy is optional;
        a Python list works too).
      - Deterministic: same activation vector → same explanation text and FVE.
      - Realistic FVE distribution: returns values in [0.35, 0.65] (matches
        the warm-start SFT range Anthropic reports before RL training).
      - Text is structured so consumers can write tests against it without
        depending on a real NLA's particular phrasing.
    """

    d_model: int
    layer_idx: int = 20
    model_id: str = "mock"
    _vocab_themes: tuple = (
        "geographic location reasoning",
        "person-level pronoun resolution",
        "syntactic dependency tracking",
        "sentiment trajectory",
        "numerical magnitude comparison",
        "stylistic register shift",
        "abstract refusal pattern matching",
        "narrative scene staging",
        "instruction-following protocol attention",
        "self-referential meta-cognition",
    )

    def explain(self, activation_vector) -> NLAExplanation:
        """Explain one activation.

        Accepts a 1-D float sequence (list, tuple, or numpy array) of
        length d_model.
        """
        vec = list(activation_vector)
        if len(vec) != self.d_model:
            raise ValueError(
                f"MockNLA expects vectors of length d_model={self.d_model}, "
                f"got {len(vec)}"
            )
        # Deterministic theme selection: hash a comma-joined string of the
        # first 32 rounded entries. This is enough entropy for theme
        # selection AND fast enough that a 1000-call test suite remains
        # fast.
        h = hashlib.sha3_256(
            ",".join(str(round(x, 6)) for x in vec[:32]).encode("utf-8")
        ).hexdigest()
        theme_idx = int(h[:4], 16) % len(self._vocab_themes)
        theme = self._vocab_themes[theme_idx]
        # FVE: deterministic function of the hash, mapped into [0.35, 0.65]
        fve_raw = int(h[4:8], 16) / 0xFFFF   # uniform [0, 1]
        fve = round(0.35 + 0.30 * fve_raw, 4)
        # L2 norm of the activation
        norm = sum(x * x for x in vec) ** 0.5

        return NLAExplanation(
            text=(
                f"[mock NLA explanation for layer {self.layer_idx}] "
                f"The activation is dominated by features that look like "
                f"{theme}. (This is a deterministic mock; the FVE and text "
                f"depend only on the input activation, not on any real model.)"
            ),
            reconstruction_fve=fve,
            model_id=self.model_id,
            layer_idx=self.layer_idx,
            activation_norm=round(norm, 6),
            extra={"mock_theme_idx": theme_idx, "mock_hash_prefix": h[:8]},
        )

    def explain_batch(self, activation_vectors) -> list[NLAExplanation]:
        return [self.explain(v) for v in activation_vectors]


# ── Adapter for the real PRISM-side NLA (when available) ────────────────────


class _PrismNLAAdapter:
    """Thin wrapper around `prism.nla.NLAExplainer` (parallel-session work).

    Imports lazily so that gemma4good doesn't hard-depend on the PRISM-side
    NLA package being installed. Construction fails (raises ImportError) in
    three cases that the factory treats as equivalent:
      1. `prism.nla` is not importable (package not installed)
      2. The model_id is not in the PRISM registry (KeyError → ImportError)
      3. Neither `server_url` nor `transport` was supplied (ValueError → ImportError)
    Case (3) is the most common — PRISM's API requires an HTTP transport or
    an injected callable; we don't have one when running locally without an
    SGLang server. Mapping all three to ImportError lets the factory's
    fallback_to_mock path do the right thing uniformly.
    """

    def __init__(self, model_id: str, **kwargs):
        try:
            from prism.nla import NLAExplainer  # type: ignore
        except ImportError as e:
            raise ImportError(
                "prism.nla is not installed. Install the PRISM-side NLA "
                "package (see D:/prism repo) or use get_explainer('mock', ...). "
                f"Original error: {e}"
            ) from e
        try:
            self._inner = NLAExplainer.from_pretrained(model_id, **kwargs)
        except (KeyError, ValueError) as e:
            # KeyError: model_id not in PRISM's NLA registry.
            # ValueError: no server_url/transport supplied.
            # Both are "real NLA not actually usable here" — translate to
            # ImportError so the factory's fallback_to_mock path treats them
            # the same way as the prism.nla-missing case.
            raise ImportError(
                f"prism.nla is installed but the explainer could not be "
                f"constructed for model_id={model_id!r}: {e}. "
                "Common causes: (a) the NLA isn't in the registry — call "
                "prism.nla.list_checkpoints() to see registered IDs; "
                "(b) you didn't pass server_url= or transport= "
                "(prism.nla.NLAExplainer needs one or the other)."
            ) from e
        self.model_id = model_id
        # PRISM's NLAExplainer exposes layer_idx via its checkpoint; we
        # re-export it for the consumer-side contract.
        ckpt = getattr(self._inner, "checkpoint", None)
        self.layer_idx = getattr(ckpt, "layer_idx", -1)

    def explain(self, activation_vector) -> NLAExplanation:
        # Translate PRISM's result type into our local NLAExplanation shape.
        inner = self._inner.explain(activation_vector)
        # The PRISM-side NLAExplanation has the same fields by design (see
        # the PRISM-side prompt's Phase 1 spec). If something changes there,
        # this is the one place we need to adapt.
        return NLAExplanation(
            text=inner.text,
            reconstruction_fve=float(inner.reconstruction_fve),
            model_id=getattr(inner, "model_id", self.model_id),
            layer_idx=getattr(inner, "layer_idx", self.layer_idx),
            activation_norm=getattr(inner, "activation_norm", -1.0),
            extra=dict(getattr(inner, "metadata", {}) or {}),
        )

    def explain_batch(self, activation_vectors) -> list[NLAExplanation]:
        return [self.explain(v) for v in activation_vectors]


# ── Factory ────────────────────────────────────────────────────────────────


def get_explainer(model_id: str, *, d_model: Optional[int] = None,
                  layer_idx: Optional[int] = None,
                  fallback_to_mock: bool = False, **kwargs) -> NLAExplainerProtocol:
    """Factory: returns a real NLA explainer if `model_id` is a known checkpoint,
    otherwise a MockNLA.

    Args:
      model_id: "mock" returns a MockNLA. Anything else attempts the PRISM-side
                NLAExplainer.from_pretrained(model_id). ImportError is raised
                if `prism.nla` isn't installed, unless fallback_to_mock=True.
      d_model: required for MockNLA (the activation dimension).
      layer_idx: required for MockNLA.
      fallback_to_mock: if True, a missing prism.nla install silently falls
                back to MockNLA with a warning. Default False (loud failure).

    Returns: an object satisfying NLAExplainerProtocol.
    """
    if model_id == "mock":
        if d_model is None:
            raise ValueError("MockNLA requires d_model")
        return MockNLA(d_model=d_model, layer_idx=layer_idx or 20)

    try:
        return _PrismNLAAdapter(model_id, **kwargs)
    except ImportError:
        if not fallback_to_mock:
            raise
        if d_model is None:
            raise ValueError(
                "fallback_to_mock=True requires d_model so MockNLA can be built"
            )
        logger.warning(
            "prism.nla not available; falling back to MockNLA (set "
            "fallback_to_mock=False for a hard failure)."
        )
        return MockNLA(d_model=d_model, layer_idx=layer_idx or 20)


# ── Module-level convenience ───────────────────────────────────────────────


def mock_explainer(d_model: int = 1536, layer_idx: int = 20) -> MockNLA:
    """Shorthand for the common test case."""
    return MockNLA(d_model=d_model, layer_idx=layer_idx)
