// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {HAICAnchor} from "../contracts/HAICAnchor.sol";

contract HAICAnchorTest is Test {
    using stdJson for string;

    HAICAnchor anchor;

    address alice = address(0xA11CE);
    address bob   = address(0xB0B);

    // Real SHA3-256 digests produced by Python utils/merkle.py.
    // Regenerated by: python onchain/gen_fixtures.py
    // sess_42   → sha3_256_hex("sess_42")
    bytes32 constant SESSION_ID =
        0xac488ab6bbb68a0c7dbe4be041e8890966da15e1f72a298299e1320e465fa8c0;
    // merkle_root of 3-message session (see gen_fixtures.py MESSAGES_3)
    bytes32 constant ROOT_A =
        0xae8293ef2c12a34eee45ecbca927e1dbb1c73bbd6e3f6def74420340fca9c07c;
    // sha3_256_hex("payload_single")
    bytes32 constant ROOT_B =
        0x80e54cd196b8f5ade36b3e1983cc4c2e6f1e450cda6889d840bb92f4f8924fef;

    event Anchored(
        bytes32 indexed sessionId,
        bytes32 indexed root,
        HAICAnchor.Kind indexed kind,
        address submitter,
        uint32  nodeCount,
        uint64  timestamp
    );

    function setUp() public {
        anchor = new HAICAnchor();
    }

    // ── Core storage/retrieval ────────────────────────────────────────────────

    function test_anchor_storesRecord() public {
        vm.prank(alice);
        anchor.anchor(SESSION_ID, ROOT_A, HAICAnchor.Kind.Session, 7);

        HAICAnchor.Anchor memory a = anchor.getAnchor(SESSION_ID);
        assertEq(a.root, ROOT_A);
        assertEq(a.submitter, alice);
        assertEq(uint8(a.kind), uint8(HAICAnchor.Kind.Session));
        assertEq(a.nodeCount, 7);
        assertGt(a.timestamp, 0);
    }

    function test_anchor_emitsEvent() public {
        vm.expectEmit(true, true, true, true);
        emit Anchored(SESSION_ID, ROOT_A, HAICAnchor.Kind.Session, alice, 7, uint64(block.timestamp));
        vm.prank(alice);
        anchor.anchor(SESSION_ID, ROOT_A, HAICAnchor.Kind.Session, 7);
    }

    function test_verify_truePath() public {
        vm.prank(alice);
        anchor.anchor(SESSION_ID, ROOT_A, HAICAnchor.Kind.Training, 12);
        assertTrue(anchor.verify(SESSION_ID, ROOT_A));
    }

    function test_verify_falsePath() public {
        vm.prank(alice);
        anchor.anchor(SESSION_ID, ROOT_A, HAICAnchor.Kind.Training, 12);
        assertFalse(anchor.verify(SESSION_ID, ROOT_B));
    }

    // ── Append-only / guard rails ─────────────────────────────────────────────

    function test_revert_appendOnly() public {
        vm.prank(alice);
        anchor.anchor(SESSION_ID, ROOT_A, HAICAnchor.Kind.Session, 7);

        vm.prank(bob);
        vm.expectRevert(abi.encodeWithSelector(HAICAnchor.AlreadyAnchored.selector, SESSION_ID));
        anchor.anchor(SESSION_ID, ROOT_B, HAICAnchor.Kind.Session, 7);
    }

    function test_revert_zeroRoot() public {
        vm.expectRevert(HAICAnchor.EmptyRoot.selector);
        anchor.anchor(SESSION_ID, bytes32(0), HAICAnchor.Kind.Session, 1);
    }

    function test_revert_zeroSessionId() public {
        vm.expectRevert(HAICAnchor.EmptySessionId.selector);
        anchor.anchor(bytes32(0), ROOT_A, HAICAnchor.Kind.Session, 1);
    }

    function test_submitterCountIncrements() public {
        vm.startPrank(alice);
        anchor.anchor(keccak256("s1"), ROOT_A, HAICAnchor.Kind.Session, 1);
        anchor.anchor(keccak256("s2"), ROOT_A, HAICAnchor.Kind.Session, 1);
        vm.stopPrank();
        assertEq(anchor.submitterCount(alice), 2);
        assertEq(anchor.submitterCount(bob), 0);
    }

    // ── Fuzz ──────────────────────────────────────────────────────────────────

    /// Fuzz: any non-zero (sessionId, root) pair should round-trip.
    function testFuzz_roundTrip(bytes32 sid, bytes32 root, uint8 kindRaw, uint32 nodes) public {
        vm.assume(sid != bytes32(0) && root != bytes32(0));
        HAICAnchor.Kind kind = HAICAnchor.Kind(uint8(bound(kindRaw, 0, 2)));
        anchor.anchor(sid, root, kind, nodes);
        assertTrue(anchor.verify(sid, root));
    }

    // ── Cross-language consistency ────────────────────────────────────────────

    /// Verify that the Python-computed SHA3-256 digests stored in fixtures.json
    /// match the constants used in this test suite.  This is the cross-language
    /// consistency check: Python utils/merkle.py ↔ Solidity constants.
    function test_crossLanguage_fixtures() public view {
        string memory json = vm.readFile("test/fixtures.json");

        bytes32 fixtureSession = json.readBytes32(".sessions.sess_42");
        assertEq(fixtureSession, SESSION_ID, "sess_42 cross-language mismatch");

        bytes32 fixtureRootA = json.readBytes32(".roots.three_message_tree");
        assertEq(fixtureRootA, ROOT_A, "three_message_tree root mismatch");

        bytes32 fixtureRootB = json.readBytes32(".roots.payload_single");
        assertEq(fixtureRootB, ROOT_B, "payload_single root mismatch");
    }
}
